jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: SonarQube Analysis
        uses: sonarsource/sonarqube-scan-action@v1.0.0
        with:
          host-url: 'http://your-server:9000'
          login: ${{ secrets.SONAR_TOKEN }}
